### ISSUE TITLE
La práctica hace al maestro

### ISSUE THREAD

**Issue by agustineavila** [jaimebit/mi_primer_repositorio#1]
Hola cómo va todo? Aunque al principio te parezca que no vale la pena subir los primeros proyectos porque son muy simples, arranca igualmente así le vas agarrando práctica tanto a git como a la consola.

**Comment by jaimebit** [comment]
parece bastante complejo al principio pero con practica voy a ir progresando
vamos a ver ahora si puedo agarrarle la mano!
